// <auto-generated />
using System;
using BuscAcoes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuscAcoes.Data.Migrations
{
    [DbContext(typeof(BuscAcoesDbContext))]
    [Migration("20210510184842_AdicionandoCampoReceberEmail")]
    partial class AdicionandoCampoReceberEmail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Acao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoNegociacao")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoNegociacao")
                        .IsUnique()
                        .HasFilter("[CodigoNegociacao] IS NOT NULL");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Acoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CodigoNegociacao = "PETR3",
                            EmpresaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CodigoNegociacao = "PETR4",
                            EmpresaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CodigoNegociacao = "PSSA3",
                            EmpresaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CodigoNegociacao = "POSI3",
                            EmpresaId = 3
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CodigoNegociacao = "PETZ3",
                            EmpresaId = 4
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CodigoNegociacao = "MSRO3",
                            EmpresaId = 5
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CodigoNegociacao = "MGLU3",
                            EmpresaId = 6
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CodigoNegociacao = "AMAR3",
                            EmpresaId = 7
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CodigoNegociacao = "CASH3",
                            EmpresaId = 8
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CodigoNegociacao = "MNDL3",
                            EmpresaId = 9
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            CodigoNegociacao = "MRVE3",
                            EmpresaId = 10
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            CodigoNegociacao = "MULT3",
                            EmpresaId = 11
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            CodigoNegociacao = "MRSA3B",
                            EmpresaId = 12
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            CodigoNegociacao = "MRSA5B",
                            EmpresaId = 12
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            CodigoNegociacao = "MRSA6B",
                            EmpresaId = 12
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            CodigoNegociacao = "BTOW3",
                            EmpresaId = 13
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            CodigoNegociacao = "B3SA3",
                            EmpresaId = 14
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            CodigoNegociacao = "BAHI3",
                            EmpresaId = 15
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            CodigoNegociacao = "BMGB4",
                            EmpresaId = 16
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            CodigoNegociacao = "BIDI11",
                            EmpresaId = 17
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            CodigoNegociacao = "BIDI3",
                            EmpresaId = 17
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            CodigoNegociacao = "BIDI4",
                            EmpresaId = 17
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            CodigoNegociacao = "BALM3",
                            EmpresaId = 18
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            CodigoNegociacao = "BALM4",
                            EmpresaId = 18
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            CodigoNegociacao = "BBSE3",
                            EmpresaId = 19
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            CodigoNegociacao = "ABCB4",
                            EmpresaId = 20
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            CodigoNegociacao = "BPAC11",
                            EmpresaId = 21
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            CodigoNegociacao = "BPAC3",
                            EmpresaId = 21
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            CodigoNegociacao = "BPAC5",
                            EmpresaId = 21
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            CodigoNegociacao = "BBAS11",
                            EmpresaId = 22
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            CodigoNegociacao = "BBAS12",
                            EmpresaId = 22
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            CodigoNegociacao = "BBAS3",
                            EmpresaId = 22
                        },
                        new
                        {
                            Id = 33,
                            Ativo = true,
                            CodigoNegociacao = "BBDC3",
                            EmpresaId = 23
                        },
                        new
                        {
                            Id = 34,
                            Ativo = true,
                            CodigoNegociacao = "BBDC4",
                            EmpresaId = 23
                        },
                        new
                        {
                            Id = 35,
                            Ativo = true,
                            CodigoNegociacao = "BKBR3",
                            EmpresaId = 24
                        },
                        new
                        {
                            Id = 36,
                            Ativo = true,
                            CodigoNegociacao = "BRQB3",
                            EmpresaId = 25
                        },
                        new
                        {
                            Id = 37,
                            Ativo = true,
                            CodigoNegociacao = "VALE3",
                            EmpresaId = 26
                        },
                        new
                        {
                            Id = 38,
                            Ativo = true,
                            CodigoNegociacao = "VLID3",
                            EmpresaId = 27
                        },
                        new
                        {
                            Id = 39,
                            Ativo = true,
                            CodigoNegociacao = "VVAR3",
                            EmpresaId = 28
                        },
                        new
                        {
                            Id = 40,
                            Ativo = true,
                            CodigoNegociacao = "VIVA3",
                            EmpresaId = 29
                        },
                        new
                        {
                            Id = 41,
                            Ativo = true,
                            CodigoNegociacao = "OIBR3",
                            EmpresaId = 30
                        },
                        new
                        {
                            Id = 42,
                            Ativo = true,
                            CodigoNegociacao = "OIBR4",
                            EmpresaId = 30
                        },
                        new
                        {
                            Id = 43,
                            Ativo = true,
                            CodigoNegociacao = "TELB3",
                            EmpresaId = 31
                        },
                        new
                        {
                            Id = 44,
                            Ativo = true,
                            CodigoNegociacao = "TELB4",
                            EmpresaId = 31
                        },
                        new
                        {
                            Id = 45,
                            Ativo = true,
                            CodigoNegociacao = "TIMS3",
                            EmpresaId = 32
                        },
                        new
                        {
                            Id = 46,
                            Ativo = true,
                            CodigoNegociacao = "CAML3",
                            EmpresaId = 33
                        },
                        new
                        {
                            Id = 47,
                            Ativo = true,
                            CodigoNegociacao = "ABEV3",
                            EmpresaId = 34
                        },
                        new
                        {
                            Id = 49,
                            Ativo = true,
                            CodigoNegociacao = "UNIP3",
                            EmpresaId = 36
                        },
                        new
                        {
                            Id = 50,
                            Ativo = true,
                            CodigoNegociacao = "UNIP5",
                            EmpresaId = 36
                        },
                        new
                        {
                            Id = 51,
                            Ativo = true,
                            CodigoNegociacao = "UNIP6",
                            EmpresaId = 36
                        },
                        new
                        {
                            Id = 52,
                            Ativo = true,
                            CodigoNegociacao = "PGMN3",
                            EmpresaId = 37
                        },
                        new
                        {
                            Id = 53,
                            Ativo = true,
                            CodigoNegociacao = "RADL3",
                            EmpresaId = 38
                        },
                        new
                        {
                            Id = 54,
                            Ativo = true,
                            CodigoNegociacao = "LINX3",
                            EmpresaId = 39
                        },
                        new
                        {
                            Id = 55,
                            Ativo = true,
                            CodigoNegociacao = "MBLY3",
                            EmpresaId = 40
                        },
                        new
                        {
                            Id = 56,
                            Ativo = true,
                            CodigoNegociacao = "QUSW3",
                            EmpresaId = 41
                        },
                        new
                        {
                            Id = 57,
                            Ativo = true,
                            CodigoNegociacao = "TOTS3",
                            EmpresaId = 42
                        },
                        new
                        {
                            Id = 58,
                            Ativo = true,
                            CodigoNegociacao = "LIPR3",
                            EmpresaId = 43
                        },
                        new
                        {
                            Id = 59,
                            Ativo = true,
                            CodigoNegociacao = "EKTR3",
                            EmpresaId = 44
                        },
                        new
                        {
                            Id = 60,
                            Ativo = true,
                            CodigoNegociacao = "EKTR4",
                            EmpresaId = 44
                        },
                        new
                        {
                            Id = 61,
                            Ativo = true,
                            CodigoNegociacao = "ATOM3",
                            EmpresaId = 45
                        },
                        new
                        {
                            Id = 62,
                            Ativo = true,
                            CodigoNegociacao = "OPGM3B",
                            EmpresaId = 46
                        },
                        new
                        {
                            Id = 63,
                            Ativo = true,
                            CodigoNegociacao = "FIGE3",
                            EmpresaId = 47
                        },
                        new
                        {
                            Id = 64,
                            Ativo = true,
                            CodigoNegociacao = "FIGE4",
                            EmpresaId = 47
                        },
                        new
                        {
                            Id = 65,
                            Ativo = true,
                            CodigoNegociacao = "AHEB3",
                            EmpresaId = 48
                        },
                        new
                        {
                            Id = 66,
                            Ativo = true,
                            CodigoNegociacao = "AHEB5",
                            EmpresaId = 48
                        },
                        new
                        {
                            Id = 67,
                            Ativo = true,
                            CodigoNegociacao = "AHEB6",
                            EmpresaId = 48
                        },
                        new
                        {
                            Id = 68,
                            Ativo = true,
                            CodigoNegociacao = "EMBR3",
                            EmpresaId = 49
                        },
                        new
                        {
                            Id = 69,
                            Ativo = true,
                            CodigoNegociacao = "TASA3",
                            EmpresaId = 50
                        },
                        new
                        {
                            Id = 70,
                            Ativo = true,
                            CodigoNegociacao = "TASA4",
                            EmpresaId = 50
                        });
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcaoId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<double>("Tolerencia")
                        .HasColumnType("float");

                    b.Property<bool>("Visualizado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasFilter("[Documento] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNasc = new DateTime(2021, 5, 10, 15, 48, 41, 406, DateTimeKind.Local).AddTicks(1695),
                            Documento = "450.129.340-32",
                            Email = "claudio@gmail.com",
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.ClienteAcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcaoId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("ReceberEmail")
                        .HasColumnType("bit");

                    b.Property<double>("Tolerancia")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("ClienteAcoes");
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.DiasIndisponiveis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .IsUnique();

                    b.ToTable("DiasIndisponiveis");
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("[Cnpj] IS NOT NULL");

                    b.HasIndex("SetorId");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Cnpj = "33.000.167/0001-01",
                            Nome = "PETROBRAS",
                            SetorId = 8
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Cnpj = "02.149.205/0001-69",
                            Nome = "PORTO SEGURO",
                            SetorId = 5
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Cnpj = "81.243.735/0001-48",
                            Nome = "POSITIVO TEC",
                            SetorId = 10
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Cnpj = "18.328.118/0001-09",
                            Nome = "PETZ",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Cnpj = "08.795.211/0001-70",
                            Nome = "MAESTROLOC",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Cnpj = "47.960.950/0001-21",
                            Nome = "MAGAZ LUIZA",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Cnpj = "61.189.288/0001-89",
                            Nome = "LOJAS MARISA",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Cnpj = "14.110.585/0001-07",
                            Nome = "MELIUZ",
                            SetorId = 10
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Cnpj = "88.610.191/0001-54",
                            Nome = "MUNDIAL",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Cnpj = "08.343.492/0001-20",
                            Nome = "MRV",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Cnpj = "07.816.890/0001-53",
                            Nome = "MULTIPLAN",
                            SetorId = 5
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            Cnpj = "01.417.222/0001-77",
                            Nome = "MRS LOGIST",
                            SetorId = 1
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            Cnpj = "00.776.574/0001-56",
                            Nome = "B2W DIGITAL",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            Cnpj = "09.346.601/0001-25",
                            Nome = "B3",
                            SetorId = 5
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            Cnpj = "45.987.245/0001-92",
                            Nome = "BAHEMA",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            Cnpj = "61.186.680/0001-74",
                            Nome = "BANCO BMG",
                            SetorId = 5
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            Cnpj = "00.416.968/0001-01",
                            Nome = "BANCO INTER",
                            SetorId = 5
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            Cnpj = "61.374.161/0001-30",
                            Nome = "BAUMER",
                            SetorId = 9
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            Cnpj = "17.344.597/0001-94",
                            Nome = "BBSEGURIDADE",
                            SetorId = 5
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            Cnpj = "28.195.667/0001-06",
                            Nome = "ABC BRASIL",
                            SetorId = 5
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            Cnpj = "30.306.294/0001-45",
                            Nome = "BTGP BANCO",
                            SetorId = 5
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            Cnpj = "00.000.000/0001-91",
                            Nome = "BRASIL",
                            SetorId = 5
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            Cnpj = "60.746.948/0001-12",
                            Nome = "BRADESCO",
                            SetorId = 5
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            Cnpj = "13.574.594/0001-96",
                            Nome = "BK BRASIL",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            Cnpj = "36.542.025/0001-64",
                            Nome = "BRQ",
                            SetorId = 10
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            Cnpj = "33.592.510/0001-54",
                            Nome = "VALE",
                            SetorId = 6
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            Cnpj = "33.113.309/0001-47",
                            Nome = "VALID",
                            SetorId = 1
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            Cnpj = "33.041.260/0652-90",
                            Nome = "VIAVAREJO",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            Cnpj = "33.839.910/0001-11",
                            Nome = "VIVARA S.A.",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            Cnpj = "76.535.764/0001-43",
                            Nome = "OI",
                            SetorId = 2
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            Cnpj = "00.336.701/0001-04",
                            Nome = "TELEBRAS",
                            SetorId = 2
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            Cnpj = "02.421.421/0001-11",
                            Nome = "TIM",
                            SetorId = 2
                        },
                        new
                        {
                            Id = 33,
                            Ativo = true,
                            Cnpj = "64.904.295/0001-03",
                            Nome = "CAMIL",
                            SetorId = 4
                        },
                        new
                        {
                            Id = 34,
                            Ativo = true,
                            Cnpj = "07.526.557/0001-00",
                            Nome = "ABEV3",
                            SetorId = 4
                        },
                        new
                        {
                            Id = 35,
                            Ativo = true,
                            Cnpj = "75.315.333/0001-09",
                            Nome = "CARREFOUR BR",
                            SetorId = 4
                        },
                        new
                        {
                            Id = 36,
                            Ativo = true,
                            Cnpj = "33.958.695/0001-78",
                            Nome = "UNIPAR",
                            SetorId = 6
                        },
                        new
                        {
                            Id = 37,
                            Ativo = true,
                            Cnpj = "06.626.253/0001-51",
                            Nome = "PAGUE MENOS",
                            SetorId = 9
                        },
                        new
                        {
                            Id = 38,
                            Ativo = true,
                            Cnpj = "61.585.865/0001-51",
                            Nome = "RAIADROGASIL",
                            SetorId = 9
                        },
                        new
                        {
                            Id = 39,
                            Ativo = true,
                            Cnpj = "06.948.969/0001-75",
                            Nome = "LINX",
                            SetorId = 10
                        },
                        new
                        {
                            Id = 40,
                            Ativo = true,
                            Cnpj = "31.553.627/0001-01",
                            Nome = "MOBLY",
                            SetorId = 10
                        },
                        new
                        {
                            Id = 41,
                            Ativo = true,
                            Cnpj = "35.791.391/0001-94",
                            Nome = "QUALITY SOFT",
                            SetorId = 10
                        },
                        new
                        {
                            Id = 42,
                            Ativo = true,
                            Cnpj = "53.113.791/0001-22",
                            Nome = "TOTVS",
                            SetorId = 10
                        },
                        new
                        {
                            Id = 43,
                            Ativo = true,
                            Cnpj = "01.104.937/0001-70",
                            Nome = "ELETROPAR",
                            SetorId = 11
                        },
                        new
                        {
                            Id = 44,
                            Ativo = true,
                            Cnpj = "02.328.280/0001-97",
                            Nome = "ELEKTRO",
                            SetorId = 11
                        },
                        new
                        {
                            Id = 45,
                            Ativo = true,
                            Cnpj = "00.359.742/0001-08",
                            Nome = "ATOMPAR",
                            SetorId = 7
                        },
                        new
                        {
                            Id = 46,
                            Ativo = true,
                            Cnpj = "02.796.775/0001-40",
                            Nome = "GAMA PART",
                            SetorId = 7
                        },
                        new
                        {
                            Id = 47,
                            Ativo = true,
                            Cnpj = "01.548.981/0001-79",
                            Nome = "INVEST BEMGE",
                            SetorId = 7
                        },
                        new
                        {
                            Id = 48,
                            Ativo = true,
                            Cnpj = "62.002.886/0001-60",
                            Nome = "SPTURIS",
                            SetorId = 3
                        },
                        new
                        {
                            Id = 49,
                            Ativo = true,
                            Cnpj = "07.689.002/0001-89",
                            Nome = "EMBRAER",
                            SetorId = 1
                        },
                        new
                        {
                            Id = 50,
                            Ativo = true,
                            Cnpj = "92.781.335/0001-02",
                            Nome = "TAURUS ARMAS",
                            SetorId = 1
                        });
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Monitoramento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<double>("PercentualVariacao")
                        .HasColumnType("float");

                    b.Property<double>("PercentualVariacaoCalculada")
                        .HasColumnType("float");

                    b.Property<double>("PrecoAcao")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.ToTable("Monitoramentos");
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Parametro", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nome");

                    b.ToTable("Parametros");

                    b.HasData(
                        new
                        {
                            Nome = "HorarioAbertura",
                            Valor = "10:00:00"
                        },
                        new
                        {
                            Nome = "HorarioFechamento",
                            Valor = "17:00:00"
                        },
                        new
                        {
                            Nome = "MonitoramentoMinutos",
                            Valor = "00:10:00"
                        },
                        new
                        {
                            Nome = "EndpointApi",
                            Valor = "https://api.hgbrasil.com/finance/stock_price?fields=only_results,price,change_percent,updated_at&symbol="
                        },
                        new
                        {
                            Nome = "ChaveApi1",
                            Valor = "78c45fea"
                        });
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Perfils");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Operador"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Cliente"
                        });
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Setores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Bens Industriais"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Comunicações"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Consumo Cíclico"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Consumo não Cíclico"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Financeiro"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Outros"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Petróleo. Gás e Biocombustíveis"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Saúde"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Utilidade Pública"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Materiais Básicos"
                        });
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasFilter("[Login] IS NOT NULL");

                    b.HasIndex("PerfilId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2021, 5, 10, 15, 48, 41, 404, DateTimeKind.Local).AddTicks(1525),
                            Login = "Admin",
                            Nome = "Administrador",
                            PerfilId = 1,
                            Senha = "e10adc3949ba59abbe56e057f20f883e"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2021, 5, 10, 15, 48, 41, 405, DateTimeKind.Local).AddTicks(8396),
                            Login = "opera",
                            Nome = "Operador",
                            PerfilId = 2,
                            Senha = "e10adc3949ba59abbe56e057f20f883e"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2021, 5, 10, 15, 48, 41, 405, DateTimeKind.Local).AddTicks(8453),
                            Login = "cliente",
                            Nome = "Cliente",
                            PerfilId = 3,
                            Senha = "e10adc3949ba59abbe56e057f20f883e"
                        });
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Acao", b =>
                {
                    b.HasOne("BuscAcoes.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany("Acoes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Alerta", b =>
                {
                    b.HasOne("BuscAcoes.Dominio.Entidades.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuscAcoes.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Cliente", b =>
                {
                    b.HasOne("BuscAcoes.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.ClienteAcao", b =>
                {
                    b.HasOne("BuscAcoes.Dominio.Entidades.Acao", "Acao")
                        .WithMany("ClienteAcoes")
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuscAcoes.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("ClienteAcoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Empresa", b =>
                {
                    b.HasOne("BuscAcoes.Dominio.Entidades.Setor", "Setor")
                        .WithMany("Empresas")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Monitoramento", b =>
                {
                    b.HasOne("BuscAcoes.Dominio.Entidades.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuscAcoes.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("BuscAcoes.Dominio.Entidades.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
